### ISSUE TITLE
investigate integrating with multiprocessing and mitogen as alternatives to execnet

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [pytest-dev/pytest-xdist#302]
from my pov there is multiple reasons

a) most people are only interested in `-n ../auto` no need to inflict execnet if its not needed
b) @flub recently pointed me to @dw's https://github.com/dw/mitogen - which to me looks like execnet done right
it also implements a lot of what i wanted to have in execnet but didn't get time to do

**Comment by dw** [comment]
Hi Ronny :)

Just as a 100 ft overview of execnet vs. Mitogen, execnet is /far/ more mature and the design is generally less adventurous. Of course that means less featureful, but it also, at least in the short term, it means more stable.

There are more notes in [docs/comparison.rst](http://mitogen.readthedocs.io/en/latest/compared.html#execnet) .. it's not linked into the main docs because some of the commentary on that page started as private notes, and they're not.. necessarily too kind on others' projects, which needs fixed first.

**Comment by RonnyPfannschmidt** [comment]
@dw based on featureset - mitogen does all the things that i wanted of execnet, and just needs a bit of love on the api side and much love on the stability side

that being said however - adding all the things i want to execnet would just make it unstable to begin with and it then would have to be re-stabilized,

also execnet has technically no more manpower behind it, its a zombie

**Comment by RonnyPfannschmidt** [comment]
closing this off - the multiprocessing experiment may need a repeat, mitogen is no longer maintained
