### ISSUE TITLE
the number of interpreters created with auto should be at most number of tests

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest-xdist#441]
At the moment even with 1 test, on a 12 core CPU 12 interpreters are spun up.

**Comment by nicoddemus** [comment]
Hi @gaborbernat,

I'm afraid this is not possible at the moment, because we only know how many tests there are after the collection phase, which is done by workers, so they need to be up by then.

I suppose we could spin a single worker initially, do the collection, and from there spin the rest of the workers based on the number of tests collected, but this will then slow down the common case where you are running more tests than the number of CPUs you have.

What you propose would be possible if the collection was done by the master node, but this is highly problematic because we would need to transfer the collected items over the wire to the workers, and test items contain a bunch of arbitrary attributes which can't be easily transferred.

I'm closing this for now but feel free to follow up with other questions. 👍

**Comment by gaborbernat** [comment]
How do tests get assigned to workers? I'm running all on a single machine but I understand the design allows to be distributed over multiple machines.

**Comment by nicoddemus** [comment]
> How do tests get assigned to workers? 

Here's a quick overview: https://github.com/pytest-dev/pytest-xdist#speed-up-test-runs-by-sending-tests-to-multiple-cpus
