### ISSUE TITLE
pytest-xdist changes verbosity of pytest automaically

### ISSUE THREAD

**Issue by AbdealiJK** [pytest-dev/pytest-xdist#46]
Normally if I run `pytest` I get:
```
coalib/tests/MakeTempTest.py ....
```
With `pytest -v` I get:
```
coalib/tests/MakeTempTest.py::MakeTempTest::test_temp_file_existence PASSED
```
With `pytest -q` I get:
```
....
```

When i run `pytest -n 2` it automatically changes the `-q` type of output. How do I get the output like 
```
coalib/tests/MakeTempTest.py ....
```
with pytest-xdist ?

**Comment by nicoddemus** [comment]
xdist overwrites the default terminal writer because the tests order is not predictable. This means that the output:

```
coalib/tests/MakeTempTest.py ....
coalib/tests/OtherTest.py ....
```

Can't be implemented without some more complicated terminal code, because tests for `coalib/tests/OtherTest.py` might start to run before all tests from `coalib/tests/MakeTempTest.py` have finished.

I think pytest-sugar is expecting support for xdist soon in Frozenball/pytest-sugar#65, might be an alternative.

**Comment by AbdealiJK** [comment]
I'll check that out - thanks !
