### ISSUE TITLE
Parallelization of the parameters

### ISSUE THREAD

**Issue by MissiaL** [pytest-dev/pytest-xdist#58]
How to run a parameter in different processes?
Example:

```
myparam = ['server1', 'server2']
@pytest.fixture(scope='session', params=myparam)
def param_session(request):
    return request.param
```

How to do that would each option run in a separate process?
For example:

```
The process "gw1" is started for the parameter "server1"
The process "gw2" is started for the parameter "server2"
```

How?
Thanks for the help

**Comment by leycec** [comment]
`xdist` should **already** parallelize test parametrization by default. See Bruno Oliveira's code snippet at [_"Running a parametrized test case in multiple CPUs."_](https://mail.python.org/pipermail/pytest-dev/2014-December/002733.html)

Nifty, eh? :rocket:

**Comment by RonnyPfannschmidt** [comment]
wrong context tho

xdist does currently not communicate about fixtures and their scope
which means it does not spread fixture runs across cpus at any level

**Comment by jxramos** [comment]
What's the bottom line on the capabilities of xdist's targeting of the unit of parallelization? If I think of [data vs task](https://en.wikipedia.org/wiki/Data_parallelism#Data_parallelism_vs._task_parallelism) parallelization where tasks are individual test cases, and the data is the parameters of a parameterized test case. Which of the two or both does xdist currently support?

There's a bunch of issues in the pytest repo itself discussing a means to constrain pytest behavior to present an execution order for xdist to work across. It's all fuzzy what the current behavior is can you clarify please @RonnyPfannschmidt  or anyone else savvy with this package. Thank you.

**Comment by nicoddemus** [comment]
> Which of the two or both does xdist currently support?

It is more of "task parallelization" because you can think of each test item as a task in that context.

> It's all fuzzy what the current behavior is can you clarify please @RonnyPfannschmidt or anyone else savvy with this package.

Well, I believe the tasks you mention all refer on ways to control how the "test items"/tasks are distributed across the workers. There are a number of options to control that currently on the README, and a few others proposed in the issues. 

Not sure what else to reply here, feel free to follow up if you like. 👍

**Comment by jxramos** [comment]
Thanks so much.

I did notice the great `--dist` option which gives some flexibility in how to batch up the parallelization units of work: currently spanning the dimension of file, module, and class. I agree those indeed seem to lean towards the task parallelization characterization.

I suppose this issue #58 seeks to expand the set of valid targets for `--dist` to parameters first, which is orthogonal to the test items themselves and sounds like it imposes some architectural demands at the moment that keep it out of reach for the time.

On another note, is this notion of _test item_ a term of art for pytest? Is it synonymous with test case, eg
`def test_XXX()`
Seems to have a general ring to it that is an umbrella term for a handful of things I'm not yet up to speed with. Is there a precise definition to _test item_ worth illuminating here? Perhaps a test case expanded across its parameters defines a set of test items?

**Comment by nicoddemus** [comment]
A test item is any item that is collected and executed as a single unit. 

For Python indeed `def test_XXX()` would be a good definition, while a parametrized test function produces one *test item* per paremetrization value. The term *item* is used because pytest is generic enough that it can be extended to execute any type of *test item*, for example [working with non-python tests](https://docs.pytest.org/en/latest/example/nonpython.html) in the docs shows an example of executing `yaml` files as test items in pytest. Another example is [pytest-cpp](https://github.com/pytest-dev/pytest-cpp), which executes C++ tests.

**Comment by subha-py** [comment]
> Thanks so much.
> 
> I did notice the great `--dist` option which gives some flexibility in how to batch up the parallelization units of work: currently spanning the dimension of file, module, and class. I agree those indeed seem to lean towards the task parallelization characterization.
> 
> I suppose this issue #58 seeks to expand the set of valid targets for `--dist` to parameters first, which is orthogonal to the test items themselves and sounds like it imposes some architectural demands at the moment that keep it out of reach for the time.
> 
> On another note, is this notion of _test item_ a term of art for pytest? Is it synonymous with test case, eg
> `def test_XXX()`
> Seems to have a general ring to it that is an umbrella term for a handful of things I'm not yet up to speed with. Is there a precise definition to _test item_ worth illuminating here? Perhaps a test case expanded across its parameters defines a set of test items?

I am in need of the exact scenario you asked solution for.
Any luck with this?
