### ISSUE TITLE
Huge performance hit after upgrading from version 1.34.0 to 2.1.0

### ISSUE THREAD

**Issue by loop0** [pytest-dev/pytest-xdist#597]
I'm not sure how to communicate this issue, but I recently had to install some dev deps and xdist got upgraded from version 1.34.0 to version 2.1.0 in my codebase, and I noticed the tests were running much slower than before, I was able to pinpoint the slow tests to xdist upgrade.

Before my tests took around 4 minutes to run with `-n 4` and after the upgrade they consistently took around 11 minutes. This is to run about 2200 tests.

Is there anything I can do to help track down this performance issue at the recent version?

**Comment by nicoddemus** [comment]
Hi @loop0,

There hasn't been any [structural changes](https://github.com/pytest-dev/pytest-xdist/blob/master/CHANGELOG.rst) that would explain such a performance difference (specially if you are running `-n 4` instead of `-n auto`). 

Perhaps compare the results of running with `--durations` between 1.34 and 2.1? That might point to a clue.

**Comment by loop0** [comment]
I tried to reproduce with the `--durations` and I couldn't. So I guess I will close this issue for now. Probably was some missed configuration on my side that was interfering.

**Comment by nicoddemus** [comment]
OK, thanks for the follow up. 👍
