### ISSUE TITLE
Test output isn't colorized with `--looponfail`

### ISSUE THREAD

**Issue by verhovsky** [pytest-dev/pytest-xdist#705]
Usually `pytest` output is green when all tests pass. With `--looponfail`, the output doesn't have any green text when all tests pass.

<img width="1280" alt="Screen Shot 2021-09-18 at 11 41 55 AM" src="https://user-images.githubusercontent.com/5687998/133897708-1b193dfb-f446-4b73-8172-90ff86d74c65.png">

**Comment by justin-f-perez** [comment]
Oddly enough, I don't get this behavior in another project... but looponfail mysteriously seems to disable assertion rewriting (I just get `AssertionError`).

a minimal repro for this bug is below. I also tested with an install from conda, which linked pytest-xdist against the the same exact build as the one that produces colored output

```sh
$ mkdir color-bug && cd color-bug
$ python3 -m venv .venv && source .venv/bin/activate && pip install pytest pytest-xdist
$ echo "def test_fail():"                  > test_assertion.py
$ echo "    assert True == False" >> test_assertion.py
$ pytest
# ....colors
$ pytest --looponfail
# ... no colors
```

additional details:
```shell
❯ pip freeze
attrs==21.2.0
execnet==1.9.0
iniconfig==1.1.1
packaging==21.3
pluggy==1.0.0
py==1.11.0
pyparsing==3.0.6
pytest==6.2.5
pytest-forked==1.3.0
pytest-xdist==2.4.0
toml==0.10.2

❯ uname -sm && sw_vers && echo "$TERM" && zsh --version
Darwin arm64
ProductName:	macOS
ProductVersion:	11.6.1
BuildVersion:	20G224
xterm-256color
zsh 5.8 (x86_64-apple-darwin20.0)
```

![image](https://user-images.githubusercontent.com/7209967/142747265-bb40cc10-824a-4325-b1b0-5356e44e4d1c.png)
![image](https://user-images.githubusercontent.com/7209967/142747270-98558750-45f1-4744-80ed-c4415341f1b4.png)

**Comment by justin-f-perez** [comment]
@verhovsky it seems `--looponfail` is more conservative when it comes to default options. You should see colored output if you use `--color=yes --looponfail`

**Comment by StanczakDominik** [comment]
I think this could be closed; the `--color=yes` flag from https://github.com/pytest-dev/pytest-xdist/issues/705#issuecomment-974854089 solves this for me. Thanks, @justin-f-perez !

**Comment by nicoddemus** [comment]
Thanks @StanczakDominik
