### ISSUE TITLE
Deprecate looponfail

### ISSUE THREAD

**Issue by nicoddemus** [pytest-dev/pytest-xdist#826]
Follow-up to #543:

> Looponfail should eventually be reimplemented in core using subprocess and a hook to register the file system watchers (so pytest plugins could support Realtime Filesystem watching)

**Comment by avylove** [comment]
It would be useful to provide a link to whatever replaced this functionality, here and in the release notes.

**Comment by nicoddemus** [comment]
The thing is that there is no real candidate for it at the moment, I'm afraid.

**Comment by avylove** [comment]
Then I'd question why it was deprecated. Deprecation requires the user to either stop using this functionality or ignore / suppress the the deprecation error. A project I maintain has both `filterwarnings = error` and `looponfailroots` in the pytest config. With 3.0.2 this results in the tests failing. So what would you recommend I do here?

Unless there is a security-driven reason for deprecation, I'd request the deprecation be removed until an alternative exists. If there is a security-driven reason, the deprecation warning should be updated with that information.

**Comment by nicoddemus** [comment]
> So what would you recommend I do here?

Do you use that functionality? If not, just remove `looponfailroots` from the config.

@RonnyPfannschmidt can you elaborate on the reasons why we deprecated loop-on-fail?

**Comment by RonnyPfannschmidt** [comment]
its broken in multiple ways (no colors, terminal disconnect, no nested xdist), and at the same is a design constraint for changing xdist itself

so in a sense is  a silent coffin nail for xdists future, we just removed the silence, its still a coffin nail

with the deprecatinon in place, we are free to remove the code as soon as a alternative exists instead of a grace period

**Comment by y2kbugger** [comment]
When you say reimplemented in core, you mean in pytest itself? Is there any plan for this?

https://github.com/search?q=%22--looponfail%22&type=code

For a feature that is often used manually at the command line, a lot of people have hardcoded it as the default.

I actually think it's a great idea to move it to core pytest because it is the only feature of pytest-xdist that I ever use, but it is a very nice feature and would be missed.

**Comment by RonnyPfannschmidt** [comment]
There is not yet a concrete plan, contribution would be welcome, but it's one big enough to most likely needs some precursor design discussion
