### ISSUE TITLE
What's the reason for ensuring 2 tests per node?

### ISSUE THREAD

**Issue by PrincipalsOffice** [pytest-dev/pytest-xdist#876]
https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/scheduler/load.py#L266
The comment doesn't seem to explain why we can't always do round robin.

**Comment by RonnyPfannschmidt** [comment]
Setupstate cache retaining needs nextitem

**Comment by PrincipalsOffice** [comment]
@nicoddemus @RonnyPfannschmidt Thanks for the context. So how does the other case work given this constraint then https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/scheduler/load.py#L257?

**Comment by amezin** [comment]
First of all,

> The comment doesn't seem to explain why we can't always do round robin.

To reuse session/class fixtures from the previous test as much as possible. IMO this comment explains it: https://github.com/pytest-dev/pytest-xdist/blob/master/src/xdist/scheduler/load.py#L266

Yes, you can do round-robin always. `LoadScheduling` had been doing it before v3.0: https://github.com/pytest-dev/pytest-xdist/commit/80130d59eabd71d4ff7cdb991624868147661632 But the performance with round-robin wasn't optimal at all https://github.com/pytest-dev/pytest-xdist/discussions/834

Round-robin distribution isn't optimal even in the "less than two tests per node" case. I kept existing code only because this corner case didn't look too important for me.

> What's the reason for ensuring 2 tests per node?

It's a separate question, but the answer is the same: to avoid unnecessary fixture setup/teardown.

https://github.com/pytest-dev/pytest-xdist/commit/67f80b7c2cb463e8361e6a1517924dfc5787eace#diff-ecec88c33adb7591ee6aa88e29b62ad52ef443611cba5e0f0ecac9b5725afdbaR7

> - fix pytest/xdist issue503: make sure that a node has usually
>  two items to execute to avoid scoped fixtures to be torn down
>  pre-maturely (fixture teardown/setup is "nextitem" sensitive).

`503` isn't a github issue number, I guess it's some other issue tracker that was in use before

**Comment by PrincipalsOffice** [comment]
> Yes, you can do round-robin always. LoadScheduling had been doing it before v3.0: https://github.com/pytest-dev/pytest-xdist/commit/80130d59eabd71d4ff7cdb991624868147661632 But the performance with round-robin wasn't optimal at all

@amezin  Is that because the tests in `self.pending` are grouped by the same module, so consecutive tests are more likely to share the same fixtures (which means round robin would forcefully separate them to different nodes)? I initially assumed that if most tests are long enough (e.g. 10mins+), the benefit of running them in individual nodes would outweight the costs of additional fixture setup/teardown.

**Comment by amezin** [comment]
> Is that because the tests in `self.pending` are grouped by the same module

Not only by module. Pytest sorts tests, taking parametrization into account:

https://github.com/pytest-dev/pytest/blob/464f29901fd437d03a3434bbcda0918c9c330868/src/_pytest/fixtures.py#L266-L345

> I initially assumed that if most tests are long enough (e.g. 10mins+), the benefit of running them in individual nodes would outweight the costs of additional fixture setup/teardown.

Not enough context. Are we talking about some specific test suite? How many tests, how many nodes?

**Comment by amezin** [comment]
If the default scheduler doesn't work well for you, try `--dist worksteal`. I'd be really interested in the feedback.

**Comment by PrincipalsOffice** [comment]
For cases like running a single test file with ~20 parallelizable tests that each takes 10+ mins to finish, it seems like round robin is the more ideal solution.  But the discussion in https://github.com/pytest-dev/pytest-xdist/pull/812 seems to suggest round robin is almost never a good choice. I agree that when there are way more tests than nodes, which is probably the most common case, round robin prob wouldn't help much at all.

**Comment by RonnyPfannschmidt** [comment]
From arguably subjective experience I arrived at the opinion that for fanning out pytest tests, round Robin is never right

**Comment by amezin** [comment]
@PrincipalsOffice so. Initially, you've created the issue about the comment not being good enough.

Do you believe it's still the case?

If you just want to discuss scheduling algorithms - I think, [Discussions](https://github.com/pytest-dev/pytest-xdist/discussions) is a more appropriate place
