### ISSUE TITLE
Limit workers to maximum needed

### ISSUE THREAD

**Issue by RoelantStegmann** [pytest-dev/pytest-xdist#899]
Generally I either run all my tests, in which case I generally use `--dist loadfile` or `--dist=loadscope`. I specify this in the `pyproject.toml` in `[tool.pytest.ini_options]`. 

When developing, however, often a single test fails and you want to re-run it. Now it seems annoying that `loadfile` spins up `auto` processes, even if there is a single file. (Similar for `loadscope`, but there I understand it might be harder to anticipate). This overhead takes quite a few seconds on my machine.

Would it be possible to scale up to `min(max_num_processes_allowed, max_needed_processes)`? In the case this turns out to be `1`, ideally we wouldn't have the overhead of parallel processing at all :)

**Comment by samamorgan** [comment]
> Under the current architecture this is not possible, because we spin up the workers before test collection happens.

@nicoddemus Can you give some clues on how this might be achieved? This is a big problem for complicated test suites, spinup time is pretty significant when debugging a single test for instance when the test suite spins up 10 workers all requiring their own database, frontend server, backend server, etc.

**Comment by flying-sheep** [comment]
Yeah, this would be great. If we would defer worker spinup until after collection, we could pass the collected items directly to `pytest_xdist_auto_num_workers` or a new hook and let users customize things.

```py
def pytest_xdist_auto_num_workers(config: pytest.Config, items: list[pytest.Item]) -> int | None:
    if len(items) < 4:
        return 0
    return None  # fall back to default behavior

**Comment by RonnyPfannschmidt** [comment]
Collection only happens on workers

**Comment by flying-sheep** [comment]
IIRC, the docs say that for some distribution strategy, there’s one initial collection and then subsets of the list are passed to workers.

If it’s not the controller doing that collection, what is?

**Comment by RonnyPfannschmidt** [comment]
Only the workers run collection

They communicate test ids to the coordinator,which then splits them into chunks to pass out to the workers

**Comment by nicoddemus** [comment]
See [How it works?](https://pytest-xdist.readthedocs.io/en/stable/how-it-works.html) in the docs for a full description on how pytest-xdist works.

The workers do the collection because the collected items (functions, classes, etc) and the metadata that pytest generates are not serializable -- for example they contain references to the config object, classes, functions, etc, all that cannot easily be serialized. IIRC the first implementations of pytest-xdist, pre-2.0, did the collection at the master and sent the collected items to the workers, however as pytest grew more features and became more complex, sending the collected items to workers became infeasible, so the strategy was changed.

I think we can close this issue as non-actionable under the current architecture, reopening it later in case somebody comes up with an idea on how to solve this.
